version: '3.4'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    
  mongoexpress:
    container_name: mongo_express
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data:
  redis_data: