version: '3.4'

services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=databaseName
    volumes:
      - ./data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - logs_volume:/app/logs
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:
  logs_volume:
