# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  TEST_MONGODB_URI: mongodb://localhost:27017/sprinApplicationTest
  REDIS_URL: redis://localhost:6379?ConnectTimeout=5000&IdleTimeOutSecs=180.

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create mongoDB Docker container      
      run: sudo docker run -d -p 27017:27017 mongo:latest
    - name: Create redis Docker container
      run: sudo docker run -d -p 6379:6379 redis:latest
    - run: npm ci
    - run: npm run test
